reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :index]
  resource :session, only: [:create, :destroy, :new]
  # Defines the root path route ("/")
  # root "articles#index"
end

reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

reddit_clone/app/models/user.rb
class User < ApplicationRecord
    validates :username, :session_token, presence:true , uniqueness: true
    validates :password, length: {minimum:6}, allow_nil:true
    validates :password_digest, presence:true

    #FIGVAPER

    attr_reader :password
    before_validation :ensure_session_token

    def password=(password)
        @password=password
        self.password_digest = BCrypt::Password.create(password)
    end

    def self.find_by_credentials(username,password)
        user = User.find_by(username: username)
        if user && user.is_password?(password)
            return user
        else
            nil
        end
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def generate_unique_session_token
        loop do 
            session_token = SecureRandom::urlsafe_base64(6)
            return session_token unless User.exists?(session_token: session_token)
        end
    end

    def ensure_session_token
        
        self.session_token ||= generate_unique_session_token
        # debugger
    end

    def reset_session_token
        self.session_token = generate_unique_session_token
        self.save!
        self.session_token
    end


end

reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user 
        @current_user = User.find_by(session_token: session[:session_token])
    end 

    def login(user)
        @current_user = user 
        session[:session_token] = @current_user.reset_session_token
    end 

    def log_out
        session[:session_token] = nil 
        current_user.reset_session_token
    end 

    def logged_in?
        !!current_user
    end 

    def require_logged_in 
        redirect_to new_session_url unless logged_in?
    end 

    def require_logged_out 
        redirect_to new_session_url if logged_in?
    end 

end

reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        render :new 
    end 

    def create
        @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
        if @user
            login(@user)
            redirect_to user_url(@user)
        else 
            @user = User.new(
            username: params[:user][:username],
            password: params[:user][:password])
            flash.now[:errors] = @user.errors.full_messages
            render :new 
        end 
    end 

    def destroy
        @current_user.log_out
        redirect_to new_session_url
    end 


end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_logged_in, only: [:show]
    before_action :require_logged_out, only: [:create, :new]

    def index 
        @users = User.all 
    end 

    def new
        @user = User.new 
    end 

    def create 
        @user = User.new(params_users)
        if @user.save 
            login(@user)
            redirect_to user_url(@user)
        else 
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end 

    def show 
        @user = User.find(params[:id])
        render :show
    end 


    private 

    def params_users
        params.require(:user).permit(:username, :password)
    end 


end

reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
  <% if flash.now[:errors]%>
      <% flash.now[:errors].each do |error| %>
      <%= error %>
      <%end %>
      <% end %>
    <%= yield %>
  </body>
</html>

reddit_clone/app/views/users/index.html.erb
<h1>All Users</h1>
<% @users.each do |user| %>
<ul> <%=user.username%></ul>
<% end %>

reddit_clone/app/views/users/new.html.erb
<form action=<%=users_url%> method= "POST">
<input type="hidden" name= "authenticity_token" value=<%= form_authenticity_token %>>
<label> Username:
<input type = "Text" name="user[username]" , value= <%= @user.username%>>
</label>

<label> Password:
<input type ="password" name="user[password]" , value= <%= @user.password%>>
</label>
<input type="submit" value='Submit'>
</form>

reddit_clone/app/views/users/show.html.erb
Welcome <%=@user.username%>

<form action=<%=session_url %> method= "POST">
<input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
 <input type="hidden" name="_method" value= "DELETE">
    <input type="submit" value= "Log Out">
</form>